name: EasyFlight
version: ${project.version}
main: me.kubajsa.easyflight.EasyFlight
api-version: 1.16
authors: [ Kubajsa ]
commands:
  fly:
    description: Enables flight
  easyflight:
    description: Main EasyFlight plugin command
    aliases: [efly, eflight]
    usage: /<command>