name: EasyFlight
version: ${project.version}
main: me.kubajsa.easyflight.EasyFlight
api-version: 1.16
authors: [ Kubajsa ]
commands:
  fly:
    description: Toggles flight
    usage: /<command> [player]
  easyflight:
    description: Main EasyFlight plugin command
    aliases: [efly, eflight]
    usage: /<command> [help|check|everyone|reload] [on|off]